apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "baseapp.fullname" . }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: {{ .Values.external_secrets.secret_store | quote }}
    kind: SecretStore
  target:
    name: {{ include "baseapp.fullname" . }}
    creationPolicy: Owner

