{{- if .Values.external_secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "baseapp.fullname" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "baseapp.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "baseapp.fullname" . }}
  labels:
    {{- include "baseapp.labels" . | nindent 4 }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: {{ .Values.external_secrets.cluster_secret_stores | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ include "baseapp.fullname" . }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "{{ .Values.cluster }}/{{ .Values.env }}/{{ .Values.app }}"
{{- end }}
